import assert from 'node:assert/strict'
import { mkdirSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { test } from 'node:test'
import { generateIndex, scanStore, validateDoc } from '../lib/indexgen.mjs'
import { makeTmpDir, writeDoc } from './helpers.mjs'

/** Build a fixture store: 2 valid docs + 1 invalid (missing trust). */
function makeStore() {
    const root = makeTmpDir()
    writeDoc(root, 'domains/routing.md', {
        title: 'Routing — where routes live',
        sources: ['file:src/router/routes.ts', 'file-glob:packages/core/src/utils/**', 'ticket:TICKET-1'],
    })
    writeDoc(root, 'decisions/why-x.md', { title: 'Why X', trust: 'T2', sources: ['user:2026-06-10'] })
    mkdirSync(path.join(root, 'domains'), { recursive: true })
    writeFileSync(
        path.join(root, 'domains/bad.md'),
        '---\nid: domains/bad\ntitle: Bad doc\nsources:\n    - file:a.ts\nderived_from_commit: abc\nharvested: 2026-06-10\nengine: manual@0.1.0\nchecks: []\nschema_version: 1\n---\nbody',
    )
    return root
}

const GOLDEN = `<!-- GENERATED by kaut index — do not edit. -->
# KAUT INDEX — test-project--12345678

| id | title | trust | derived_from_commit | sources(files) |
|---|---|---|---|---|
| decisions/why-x | Why X | T2 | aaaaaaaaaaaa | 0 |
| domains/routing | Routing — where routes live | T1 | aaaaaaaaaaaa | 2 |

## Gaps

(none)

## Invalid

- \`domains/bad.md\` — missing required field "trust"; derived_from_commit "abc" is not a commit hash (7–40 hex chars)
`

test('golden: fixture store renders the exact expected INDEX.md (gate G2 round-trip)', () => {
    const root = makeStore()
    const { content, docs, invalid } = generateIndex(root, 'test-project--12345678')
    assert.equal(content, GOLDEN)
    assert.equal(docs.length, 2)
    assert.equal(invalid.length, 1)
})

test('scanStore lists only .md under layer dirs, sorted', () => {
    const root = makeStore()
    writeFileSync(path.join(root, 'not-a-layer.md'), 'ignored')
    mkdirSync(path.join(root, 'map'), { recursive: true })
    writeFileSync(path.join(root, 'map/notes.txt'), 'ignored')
    assert.deepEqual(scanStore(root), ['decisions/why-x.md', 'domains/bad.md', 'domains/routing.md'])
})

test('validateDoc: id must match the store-relative path', () => {
    const root = makeTmpDir()
    writeDoc(root, 'domains/a.md', { id: 'domains/WRONG' })
    const raw = `---
id: domains/WRONG
title: T
sources:
    - file:a.ts
derived_from_commit: abc
harvested: 2026-06-10
engine: manual@0.1.0
trust: T1
checks: []
schema_version: 1
---
`
    const v = validateDoc('domains/a.md', raw)
    assert.equal(v.ok, false)
    assert.match(v.errors.join(' '), /does not match path/)
})

test('validateDoc: bad source grammar and unknown trust are reported together', () => {
    const raw = `---
id: domains/a
title: T
sources:
    - bogus-source
derived_from_commit: abc
harvested: 2026-06-10
engine: manual@0.1.0
trust: T9
checks: []
schema_version: 1
---
`
    const v = validateDoc('domains/a.md', raw)
    assert.equal(v.ok, false)
    assert.match(v.errors.join(' | '), /invalid source/)
    assert.match(v.errors.join(' | '), /unknown trust "T9"/)
})

test('validateDoc: unparseable frontmatter is a single clear error', () => {
    const v = validateDoc('domains/a.md', 'no frontmatter at all')
    assert.equal(v.ok, false)
    assert.match(v.errors[0], /must start with "---"/)
})
