/**
 * Workspace registry reader (engine v0.3.0, workspace thin slice).
 *
 * Registries live in `~/.kaut/workspaces/<name>.json` — one per workspace, GENERATED by
 * `kaut workspace init` from a conductor manifest. The manifest is the single source of
 * truth; a registry is a derived copy. This module only READS registries: it resolves a
 * member-repo name to its absolute path for `repo:` source existence checks (stale.mjs).
 *
 * `KAUT_WORKSPACES_DIR` overrides the directory (tests use it). An unreadable registry
 * file is skipped — the resolver then returns null and the verdict engine errs toward
 * stale, never toward fresh.
 */
import { existsSync, readdirSync, readFileSync } from 'node:fs'
import path from 'node:path'
import { kautHome } from './discover.mjs'

/** @type {Map<string, object[]>} per-process cache: dir → parsed registries */
const cache = new Map()

/**
 * @param {Record<string, string|undefined>} [env]
 * @returns {string} the workspaces registry directory
 */
export function workspacesDir(env = process.env) {
    return env.KAUT_WORKSPACES_DIR || path.join(kautHome(env), 'workspaces')
}

/**
 * Load every parseable registry in the directory (file-name order — deterministic).
 * @param {string} [dir]
 * @returns {object[]}
 */
export function loadRegistries(dir = workspacesDir()) {
    if (cache.has(dir)) return /** @type {object[]} */ (cache.get(dir))
    const out = []
    if (existsSync(dir)) {
        for (const f of readdirSync(dir).filter((n) => n.endsWith('.json')).sort()) {
            try {
                out.push(JSON.parse(readFileSync(path.join(dir, f), 'utf8')))
            } catch {
                // unreadable registry — skip; resolveRepoPath returns null and the
                // freshness engine treats the source as unverifiable (err-toward-stale)
            }
        }
    }
    cache.set(dir, out)
    return out
}

/**
 * Resolve a workspace member repo name to its absolute path.
 * @param {string} name repo name as listed in the registry
 * @param {string} [dir]
 * @returns {string|null} absolute repo path, or null when no registry knows the name
 */
export function resolveRepoPath(name, dir = workspacesDir()) {
    for (const reg of loadRegistries(dir)) {
        for (const r of reg.repos ?? []) if (r.name === name && r.path) return r.path
    }
    return null
}

/**
 * Resolve a store root to its registry entry's write-grant context. Matches a member by
 * `storeRoot`, or the workspace system store by `systemStore.root`. Returns null when no registry
 * knows the store — a single-store / non-workspace store, which the gate treats as free-write
 * (open-until-configured, byte-identical to pre-gate behaviour).
 * @param {string} root store root
 * @param {string} [dir]
 * @returns {{writePolicy: Record<string,string>|null, storePolicy: string|null}|null}
 */
export function resolveWriteEntry(root, dir = workspacesDir()) {
    for (const reg of loadRegistries(dir)) {
        for (const r of reg.repos ?? [])
            if (r.storeRoot === root) return { writePolicy: r.writePolicy ?? null, storePolicy: r.storePolicy ?? null }
        if (reg.systemStore && reg.systemStore.root === root)
            return { writePolicy: reg.systemStore.writePolicy ?? null, storePolicy: null }
    }
    return null
}

/**
 * The OTHER store roots in the SAME workspace registry as `root` (creation-distinction,
 * Mechanism A). Used to decide whether a doc id is NOVEL in the deployment or a CANONICAL type
 * that already exists elsewhere (the first repo's first `runbook/local-debug` is owner-gated; from
 * the second repo onward the pattern is established → Tier A). Members + system store, excluding
 * `root`. Returns [] when no registry knows `root` — a single-store / non-workspace store, where the
 * gate's early return means this is never consulted anyway.
 * @param {string} root the writing store's root
 * @param {string} [dir]
 * @returns {string[]} sibling store roots
 */
export function deploymentSiblingStoreRoots(root, dir = workspacesDir()) {
    for (const reg of loadRegistries(dir)) {
        const roots = []
        for (const r of reg.repos ?? []) if (r.storeRoot) roots.push(r.storeRoot)
        if (reg.systemStore && reg.systemStore.root) roots.push(reg.systemStore.root)
        if (roots.includes(root)) return roots.filter((r) => r !== root)
    }
    return []
}

/**
 * Resolve the write grant for a (layer, provenance) against an entry's `writePolicy`.
 * Open-until-configured: no `writePolicy`, or a layer the map does not cover (no `<layer>` and no
 * `*`), ⇒ null (free — not governed). map/* discriminates BY PROVENANCE: an adapter-generated map doc
 * (`engine: compose-map@`/`route-map@`/`pkg-graph@`) takes the configured `map` grant; a hand-authored
 * map doc (any other `engine:`) is forced `owner` whenever map is governed. Any non-`agent` configured
 * value normalises to `owner` (closed within a governed layer; a typo never silently grants).
 * @param {{writePolicy?: Record<string,string>|null}|null} entry
 * @param {string} layer
 * @param {string} provenance the doc's frontmatter `engine:` value
 * @returns {'agent'|'owner'|null}
 */
export function resolveWritePolicy(entry, layer, provenance) {
    const wp = entry && entry.writePolicy
    if (!wp || typeof wp !== 'object') return null
    const g = wp[layer] ?? wp['*'] ?? null
    if (g === null) return null // layer not governed → free (open-until-configured)
    if (layer === 'map' && !/^(compose-map|route-map|pkg-graph)@/.test(String(provenance || ''))) return 'owner'
    return g === 'agent' ? 'agent' : 'owner'
}

/** Drop the per-process registry cache (tests; `workspace init` after regenerating). */
export function clearRegistryCache() {
    cache.clear()
}
